export interface Options {
	fontFamilyPref: boolean;
	fontFamily: string;
	fontSizePref: boolean;
	fontSize: string;
	fontWeightPref: boolean;
	fontWeight: string;
	fontColorPref: boolean;
	fontColor: string;
	fontOpacityPref: boolean;
	fontOpacity: string;
	effectLetterSpacingPref: boolean;
	effectLetterSpacing: string;
	effectWordSpacingPref: boolean;
	effectWordSpacing: string;
	effectLineHeightPref: boolean;
	effectLineHeight: string;
	effectTextMarginPref: boolean;
	effectTextMargin: string;
	effectTextVertPosition: string;
	effectTextHorPosition: string;
	effectTextTransform: string;
	effectStrokePref: boolean;
	effectStrokeWidth: string;
	effectStrokeColor: string;
	effectShadowPref: boolean;
	effectShadowOffsetX: string;
	effectShadowOffsetY: string;
	effectShadowColor: string;
	effectShadowBlur: string;
	effectShadowOpacity: string;
	effectTextBlurPref: boolean;
	effectTextBlur: string;
	backgroundType: string;
	backgroundColorOpacityPref: boolean;
	backgroundColor: string;
	backgroundOpacity: string;
	backgroundPaddingPref: boolean;
	backgroundPadding: string;
	backgroundRadiusPref: boolean;
	backgroundRadius: string;
	captionSegmentStyles: string;
	captionWindowStyles: string;
}

export const defaults: Options = {
	fontFamilyPref: false,
	fontFamily: "",
	fontSizePref: false,
	fontSize: "100",
	fontWeightPref: false,
	fontWeight: "400",
	fontColorPref: false,
	fontColor: "#ffffff",
	fontOpacityPref: false,
	fontOpacity: "100",
	effectLineHeightPref: false,
	effectLineHeight: "100",
	effectTextMarginPref: false,
	effectTextMargin: "0",
	effectTextVertPosition: "default",
	effectTextHorPosition: "default",
	effectLetterSpacingPref: false,
	effectLetterSpacing: "0",
	effectWordSpacingPref: false,
	effectWordSpacing: "0",
	effectTextTransform: "none",
	effectStrokePref: false,
	effectStrokeWidth: "0",
	effectStrokeColor: "#000000",
	effectShadowPref: false,
	effectShadowOffsetX: "0",
	effectShadowOffsetY: "0",
	effectShadowColor: "#000000",
	effectShadowBlur: "0",
	effectShadowOpacity: "50",
	effectTextBlurPref: false,
	effectTextBlur: "0",
	backgroundType: "window",
	backgroundColorOpacityPref: false,
	backgroundColor: "#000000",
	backgroundOpacity: "50",
	backgroundPaddingPref: false,
	backgroundPadding: "0",
	backgroundRadiusPref: false,
	backgroundRadius: "0",
	captionSegmentStyles: "",
	captionWindowStyles: ""
};
